In [4]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
df['target'] = iris.target
df['species'] = df['target'].apply(lambda x: iris.target_names[x])
df.head(125)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   

     target    species  
0         0     setosa  
1         0     setosa  
2         0     setosa  
3         0     setosa  
4         0     setosa  
..      ...        ...  
120       2  virginica  
121       2  virginica  
122       2  virginica  
123       2  virginica  
124       2  virginica  

[125 rows x 6 columns]

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

x = df.drop(['target','species'],axis = 1)
y = df['species']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)

print(f'Scaled X-train {x_train_scaled}')

x_test_scaled = scaler.transform(x_test)

log_reg = LogisticRegression(multi_class = 'ovr',solver = 'liblinear')

log_reg.fit(x_train_scaled,y_train)

y_pred = log_reg.predict(x_test_scaled)
print(y_pred,y_test)

Scaled X-train [[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.72969227  0.95664273]
 [ 0.72020757  0.30929911  0.44316389  0.4227026 ]
 [-0.74255534  0.98006827 -1.27600637 -1.31260282]
 [-0.98634915  1.20365799 -1.33331205 -1.31260282]
 [-0.74255534  2.32160658 -1.27600637 -1.44608785]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993  0.75647855  0.44316389  0.55618763]
 [ 1.08589829  0.08570939  0.55777524  0.4227026 ]
 [-0.49876152  1.87442714 -1.39061772 -1.04563275]
 [-0.49876152  1.4272477  -1.27600637 -1.31260282]
 [-0.37686461 -1.47941864 -0.01528151 -0.24472256]
 [ 0.59831066 -0.58505976  0.78699794  0.4227026 ]
 [ 0.72020757  0.08570939  1.01622064  0.8231577 ]
 [ 0.96400139 -0.13788033  0.38585821  0.28921757]
 [ 1.69538284  1

/home/aashish/Desktop/vsCode/hackmedia/python/python_venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [ ]:
print('please input the following features to predict the iris flower species:')
sepal_length = float(input('sepal length (in cm): '))
sepal_width = float(input('sepal width (in cm): '))
petal_length = float(input('petal length (in cm): '))
petal_width = float(input('petal width (in cm): '))

In [9]:
conf_matrix = confusion_matrix(y_test,y_pred)
print('confusion Matrix:\n',conf_matrix)

class_report = classification_report(y_test, y_pred)
print('classification report: \n',class_report)

accuracy = accuracy_score(y_test,y_pred)
print('accuracy score:\n',accuracy)

confusion Matrix:
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
classification report: 
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.89      0.94         9
   virginica       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

accuracy score:
 0.9666666666666667


In [15]:
from sklearn.neighbors import KNeighborsClassifier

x = df.drop(['target','species'],axis = 1)
y = df['species']

x_train, x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)

x_test_scaled = scaler.transform(x_test)

knn = KNeighborsClassifier(n_neighbors = 5)

knn.fit(x_train_scaled,y_train)

y_pred_knn = knn.predict(x_test_scaled)

In [16]:
print(f'Confusion matrix:\n{confusion_matrix(y_test,y_pred_knn)}')
print(f'Classification matrix:\n{classification_report(y_test,y_pred_knn)}')
print(f'Accuracy matrix:\n{accuracy_score(y_test,y_pred_knn)}')

Confusion matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification matrix:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy matrix:
1.0
