<h1> Numpy and Pandas Understanding</h1>
<p>This notebook is about learning and understanding of basics of numpy and pandas.</p>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvEfXHLIJLACY1DI30rAzDlbekLkgFXYm1DA&s" alt="numpy logo">

In [1]:
num_list = [i for i in range (10)]
sum_value = 0

In [2]:
for i in num_list:
    sum_value += i
print(sum_value)

45


In [3]:
print(sum(num_list))

45


<h2>Understanding Numpy</h2>
<p>installing Numpy from jupyter notebook </p>

In [4]:
!pip3 install numpy

In [5]:
import numpy as np

# myarray = np.zeros(4)
# print(myarray,type(myarray))

myarray = np.array(num_list)
print(myarray,type(myarray))

print(num_list,type(num_list))


[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [6]:
print(myarray.sum())
print(myarray.mean())
print(myarray.std())
print(myarray.max())
print(myarray.min())

45
4.5
2.8722813232690143
9
0


In [7]:
import statistics
print(sum(num_list))
print(min(num_list))
print(max(num_list))
print(sum(num_list)/len(num_list))
print(statistics.stdev(num_list))

45
0
9
4.5
3.0276503540974917


In [8]:
matrix = np.array([[1,20],[20,1]])
print(matrix,type(matrix))

zeromatrix = np.zeros((2,2))
print(zeromatrix,type(zeromatrix))

onematrix = np.ones((2,2))
print(onematrix,type(onematrix))

[[ 1 20]
 [20  1]] <class 'numpy.ndarray'>
[[0. 0.]
 [0. 0.]] <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] <class 'numpy.ndarray'>


In [9]:
matrixA = np.array([[1,2,11],[1,7,13],[1,21,1]])
matrixB = np.array([[1,4,3],[5,6,8],[9,2,3]])
# print(matrixA +matrixB)
# print(matrixA - matrixB)
print(matrixA * matrixB)
print(np.dot(matrixA,matrixB))
print(np.cross(matrixA,matrixB))

[[  1   8  33]
 [  5  42 104]
 [  9  42   3]]
[[110  38  52]
 [153  72  98]
 [115 132 174]]
[[ -38    8    2]
 [ -22   57  -29]
 [  61    6 -187]]


<p>input form user</p>

In [10]:
m = int(input('number of m:'))
n = int(input('number of n:'))
matrix = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        matrix[i][j]=int(input(f'enter {i}{j}: '))
print(matrix)

[[ 3.  3.  3.]
 [ 1.  5.  7.]
 [ 9. 10.  6.]]


In [11]:
determinantA = np.linalg.det(matrixA)
print(determinantA,type(determinantA))

determinantB = np.linalg.det(matrixB)
print(determinantB,type(determinantB))

transposed = matrixA.T
print(transposed)

solution = np.linalg.solve(matrixA,matrixB)
print(solution)

-88.00000000000003 <class 'numpy.float64'>
97.99999999999996 <class 'numpy.float64'>
[[ 1  1  1]
 [ 2  7 21]
 [11 13  1]]
[[ -4.77272727  -2.36363636 -10.01136364]
 [  0.63636364   0.18181818   0.56818182]
 [  0.40909091   0.54545455   1.07954545]]


In [12]:
arrayofnumbers = np.linspace(1,5,10)
print(arrayofnumbers)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [13]:
print(np.sqrt([4,2]))
print(np.exp(10))
print(np.sin([1,2,3,4]))

[2.         1.41421356]
22026.465794806718
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
